window.globals = {};
globals.require = loadScript;
globals.te = te;
globals.break = function() {
    var origin = location.href;
    location.reload();
    alert('URL: '+origin);
};
globals.kill = function() {
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    globals.require('bootloader-2-11-min.js');
    setTimeout(20000, function(){});
    location.reload();
};
